# Force OS X.
language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.2
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7.1
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode6.4
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.3
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system
    - env: OSX=10.9
      os: osx
      rvm: system

before_install:
  - cd /usr/local
  - git remote set-url origin https://github.com/xu-cheng/homebrew-test.git

script:
  - brew config
  - time brew update
  - git symbolic-ref --short HEAD
  - git status
  - brew config
  - brew readall --aliases
  - brew tests
  - brew install tree
  - time brew update

notifications:
  email: never
